### ISSUE TITLE
GPU version of your Q-learning demo : enhancement

### ISSUE THREAD

**Issue by AjayTalati** [karpathy/convnetjs#27]
Dear Andrej,

I really like your deep q-learning demo page :+1:  May I ask if you, or anyone you know have tried to use Torch, Theano or Caffe, with iPython notebooks or something else to build a GPU version of the demo? 

I realize this would be a lot of work, but it would also be a lot of fun :+1:  Since you have made the big first step of proof of principle that it can be done, it also gives a clear map of how to do it!

Best wishes, Aj

**Comment by karpathy** [comment]
Thanks! I'm not aware of any other implementation right now.
