### ISSUE TITLE
Confusion about formula for H2 and W2 and D2

### ISSUE THREAD

**Issue by ArEnSc** [karpathy/convnetjs#43]
In your code you specify that 

```javascript
layer_defs.push({type:'input', out_sx:32, out_sy:32, out_depth:3}); // declare size of input
// output Vol is of size 32x32x3 here
```
This is fine and makes sense

how ever this volume calculation is odd to me.

```javascript
layer_defs.push({type:'conv', sx:5, filters:16, stride:1, pad:2, activation:'relu'});
// the layer will perform convolution with 16 kernels, each of size 5x5.
// the input will be padded with 2 pixels on all sides to make the output Vol of the same size
// output Vol will thus be 32x32x16 at this point
```
In your lecture notes you say

H2 = (H1 - F) + (2 * P) / S + 1
H2 = (32 - 5) + (2 * 2)/ 1 + 1
H2 = (27) + (4) / 2 
H2 = 15.5
W2 = (W1 - F) + (2 * P) / S + 1
W2 = 15.5

D2 = K
D2 = 16
Resulting Volume 
15.5 * 15.5 * 16

I am confused about how you arrived at 32 x 32 x 16 volume

**Comment by karpathy** [comment]
H2 = (32 - 5) + (2 * 2)/ 1 + 1 = 32 - 5 + 4 + 1 = 32, not 15.5. This is
elementary school stuff ;)

also make sure you're not missing brackets, the formula is
H2 = ((H1 - F) + (2 * P)) / S + 1

**Comment by ArEnSc** [comment]
LOL OMg I need sleep thanks hahahaha
