### ISSUE TITLE
Convnetjs is not bower installable.

### ISSUE THREAD

**Issue by levicc00123** [karpathy/convnetjs#7]
If you don't know, [Bower](http://www.bower.io) is a package manager for javascript libraries,  I use bower when working on my web apps, and It'd be useful if I could add convnetjs to my current project. I've taken the liberty of creating a bower.json file and I'll have a pull request for you in a jiffy.

**Comment by mryellow** [comment]
It's true.... Without having the compiled versions you're left with an empty directory which can't be used in a deployment. This means the `npm` and `bower` installs are incomplete.
